# Required parameters
engine: "Isaac"
robots:
  R1:
    urdf_path: "robots/ur5/urdf/ur5_with_gripper.urdf"
    position: [0, 0, 0.63]
    observable_joints: ["ee_link"]
urdfs:
  Table:
    urdf_path: "table/table.urdf"
    type: "Table"
    position: [0, 0, 0]
    orientation: [1, 0, 0, 0]
obstacles:
  TargetCube:
    position: [[-0.65, -0.4, 0.64], [0.65, 0.4, 1]]
    color: [1, 0, 0]
    collision: False
    observable: True
    type: "Cube"
  Sphere:
    position: [0.4, 0.3, 0.8]
    collision: True
    observable: True
    type: "Sphere"
  Sphere2:
    position: [0.4, -0.3, 0.9]
    collision: True
    observable: True
    type: "Sphere"
  Cylinder:
    position: [-0.45, 0.4, 0.7]
    collision: True
    observable: True
    type: "Cylinder"
rewards:
  TargetDistance:
    obj1: "TargetCube"
    obj2: "R1/ee_link"
    type: "Distance"
  CollisionDetection:
    obj: "R1"
    weight: -5
    type: "Collision"
resets:
  # Name of reset conditions is irrelevant
  one:
    distance: "TargetDistance"
    min_distance: 0
    max_distance: 1.5
    type: "DistanceReset"
  two:
    max: 100
    type: "TimestepsReset"
  three:
    obj: "R1"
    max: 1
    type: "CollisionReset"

# optional parameters
asset_path: "./data"
step_size: 0.00416666666
step_count: 1
headless: True
num_envs: 9
env_offset: [4, 4]