# Required parameters
engine: "Isaac"
robots:
  R1:
    urdf_path: "robots/ur5/urdf/ur5_with_gripper.urdf"
    position: [0, 0, 0.63]
    observable_joints: ["ee_link"]
urdfs:
  Table:
    urdf_path: "table/table.urdf" #workspace: [[-0.65,-0.40,0.64],[0.65,0.40,1.00]]
    type: "Table"
    position: [0, 0, 0]
    orientation: [1, 0, 0, 0]
obstacles:
  Cube:
    position: [[-0.65,-0.40,0.64],[0.65,0.40,1.00]]
    collision: True
    observable: True
    type: "Cube"
  Sphere:
    position: [[-0.65,-0.40,0.64],[0.65,0.40,1.00]]
    collision: True
    observable: True
    type: "Sphere"
  Cylinder:
    position: [[-0.65,-0.40,0.64],[0.65,0.40,1.00]]
    collision: True
    observable: True
    type: "Cylinder"
rewards:
  CollisionDetection:
    obj: "R1"
    weight: -5
    type: "Collision"
  Timestep:
    weight: 1
    type: "ElapsedTimesteps"
resets:
  # Name of reset conditions is irrelevant
  one:
    max: 100
    type: "TimestepsReset"
  two:
    obj: "R1"
    max: 1
    type: "CollisionReset"

# optional parameters
asset_path: "./data"
step_size: 0.00416666666
step_count: 1
headless: True
num_envs: 9
env_offset: [4, 4]