# Required parameters
engine: "Isaac"
robots:
  R1:
    urdf_path: "robots/ur5/urdf/ur5_with_gripper.urdf"
    position: [0, 0, 0.63]
    observable_joints: ["ee_link"]
urdfs:
  Table:
    urdf_path: "table/table.urdf"
    type: "Table"
    position: [0, 0, 0]
    orientation: [1, 0, 0, 0]
obstacles:
  TargetCube:
    position: [[-0.65, -0.4, 0.64], [0.65, 0.4, 1]]
    color: [1, 0, 0]
    collision: False
    observable: True
    type: "Cube"
  DynamicCube:
    position: [[0.2, 0.2, 0.8],[0.3, 0.3, 0.8]]
    collision: True
    observable: True
    velocity: 1
    static: False
    type: "Sphere"
rewards:
  TargetDistance:
    obj1: "TargetCube"
    obj2: "R1/ee_link"
    type: "Distance"
  CollisionDetection:
    obj: "R1"
    weight: -5
    type: "Collision"
resets:
  # Name of reset conditions is irrelevant
  one:
    distance: "TargetDistance"
    min_distance: 0
    max_distance: 1.5
    type: "DistanceReset"
  two:
    max: 100
    type: "TimestepsReset"
  three:
    obj: "R1"
    max: 1
    type: "CollisionReset"

# optional parameters
asset_path: "./data"
step_size: 0.00416666666
step_count: 1
headless: False
num_envs: 1
env_offset: [4, 4]