run:
  engine: "PyBullet"
  load_model: False
  algorithm:
    type: "PPO"
    learning_rate: 0.0003
    batch_size: 2048 

train:
  logging: 0
  timesteps: 1500000 
  save_freq: 100000

evaluation:
  timesteps: 1500000 

env:
  num_envs: 9
  env_offset: [4, 4]
  headless: False
  step_size: 0.00416666666
  step_count: 1

  robots:
    - name: "R1"
      urdf_path: "robots/ur5/urdf/ur5_with_gripper.urdf"
      position: [0, 0, 0.63]
      observable_joints: ["ee_link"]
      control_type: "Velocity"  

  urdfs:
    - name: "Table" # workspace: [[-0.65,-0.40,0.64],[0.65,0.40,1.00]]
      urdf_path: "table/table.urdf"
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]
  
  obstacles:    
    - name: "DynamicCube"
      position: [[-0.65,-0.4,0.64],[0.65,0.4,1]]
      endpoint: [[-0.65,-0.4,0.64],[0.65,0.4,1]]
      velocity: 0.3
      static: False
      collision: True
      observable: True
      type: "Cube"
    
    - name: "DynamicCylinder"
      position: [-0.45, 0.4, 0.7]
      endpoint: [0.65,0.4,1]
      velocity: 0.3
      static: True
      collision: True
      observable: True
      type: "Cylinder"
  
  rewards:
    - name: "CollisionDetection"
      obj: "R1"
      weight: -1
      type: "Collision"
    
    - name: "Timestep"
      type: "ElapsedTimesteps"

  resets:   
    - max: 1000
      type: "TimestepsReset"
    
    - obj: "R1"
      max: 10
      reward: -5
      type: "CollisionReset"